:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default
  - mailers
  - [urgent, 2]

:schedule:
  check_all_urls:
    cron: '*/15 * * * *'  # Every 15 minutes
    class: CheckAllUrlsJob
    queue: default
